#!/usr/bin/env bash
code_id=$1
phen_stats_file=$2
sum_stats_file=$3

# Could do a zcat/awk symlink to homogenise
# Flag for if sQTL (ranges) or eQTL (genes)
zcat /home/${phen_stats_file} | awk '{print $1,$19,$25,$26,$29,$2,$3,$4,$5}' | tail -n+2 > /home/${phen_stats_file}_formatted
zcat /home/${sum_stats_file} | tail -n+2 | sed 's|_|\t|g' | sed 's|chr||g' | awk '{print $6,$1":"$2"_"$3"/"$4,$7,$10,$11,$12,$13,$1,$2,$3,$4,$1":"$2"_"$3"/"$4}' > /home/${sum_stats_file}_formatted

mysql -u root -ptest <<END_INPUT

use interval;

CREATE TABLE \`${code_id}_phenstats\` (
 \`phenotype_id\` varchar(50) NOT NULL,
 \`variant_rsid\` varchar(30) NOT NULL,
 \`slope\` float NOT NULL,
 \`slope_se\` float NOT NULL,
 \`qval\` double NOT NULL,
 \`gene_name\` varchar(200) NOT NULL,
 \`gene_chr_str\` varchar(20) NOT NULL,
 \`gene_start\` int(11) NOT NULL,
 \`gene_end\` int(11) NOT NULL,
 \`z_score\` float GENERATED ALWAYS AS (\`slope\` / \`slope_se\`) VIRTUAL,
 \`z_score_abs\` float GENERATED ALWAYS AS (abs(\`slope\` / \`slope_se\`)) VIRTUAL,
 \`gene_chr_int\` int(11) GENERATED ALWAYS AS (replace(\`gene_chr_str\`,'chr','')) VIRTUAL,
 PRIMARY KEY (\`phenotype_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOAD DATA LOCAL INFILE '/home/${phen_stats_file}_formatted' INTO TABLE \`${code_id}_phenstats\` FIELDS TERMINATED BY ' ' LINES TERMINATED BY '\n' IGNORE 0 LINES;


CREATE TABLE \`${code_id}_sumstats\` (
  \`phenotype_id\` varchar(50) NOT NULL,
  \`variant_rsid\` varchar(30) NOT NULL,
  \`tss_distance\` int(11) NOT NULL,
  \`af\` float NOT NULL,
  \`pval_nominal\` double NOT NULL,
  \`slope\` float NOT NULL,
  \`slope_se\` float NOT NULL,
  \`variant_chr\` int(11) NOT NULL,
  \`variant_pos\` int(11) NOT NULL,
  \`variant_ref\` varchar(10) NOT NULL,
  \`variant_alt\` varchar(10) NOT NULL,
  \`variant_posid\` varchar(50) NOT NULL,
  \`id\` int(11) NOT NULL AUTO_INCREMENT,
  \`slope_inv\` float GENERATED ALWAYS AS (-1 * \`slope\`) VIRTUAL,
  \`z_score_abs\` float GENERATED ALWAYS AS (abs(\`slope\` / \`slope_se\`)) VIRTUAL,
  PRIMARY KEY (\`id\`),
  KEY \`phenotype_id\` (\`phenotype_id\`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

LOAD DATA LOCAL INFILE '/home/${sum_stats_file}_formatted' INTO TABLE \`${code_id}_sumstats\` FIELDS TERMINATED BY ' ' LINES TERMINATED BY '\n' IGNORE 0 LINES;


INSERT INTO \`projects\` (\`code_name\`, \`nice_name\`) VALUES ('${code_id}', '${code_id}'); 


END_INPUT

rm /home/${phen_stats_file}_formatted
rm /home/${sum_stats_file}_formatted
